@startuml
title getDatasetDescription use case
autonumber

actor DatasetUser as User

participant "My datasets view" as DatasetsView
participant "Dataset detail view" as View
participant "DatasetDetailPresenter" as Presenter
participant "datasets.controller.ts" as Controller
participant "uc.dataset" as UseCase
participant "CombinedClient" as Client
participant "Dataset API\nGET /datasets/{id}/description" as Http

User ->> DatasetsView : Open description tab
DatasetsView ->> Controller : getDatasetDescription(datasetId)
Controller ->> UseCase : getDatasetDescription(datasetId)
UseCase -> Client : getDatasetDescription(datasetId)
Client ->> Http : GET /datasets/{id}/description
Http ->> Client : DatasetDescription
Client --> UseCase : DatasetDescription
UseCase ->> Presenter : present(DatasetDescription)
Presenter ->> View : render(DatasetDescription)
View ->> User : Show dataset description

@enduml


