@startuml
title listDatasets use case
autonumber

actor User

participant "Datasets list view" as View
participant "DatasetsPresenter" as Presenter
participant "datasets.controller.ts" as Controller
participant "uc.dataset" as UseCase
participant "CombinedClient" as Client
participant "Dataset API\nPOST /datasets" as Http

User -> View : Open datasets page
View -> Presenter : mount(filter, page, size)
Presenter -> Controller : loadDatasets(filter, page, size)
Controller -> UseCase : listDatasets(filter, page, size)
UseCase -> Client : listDatasets(filter, page, size)
Client -> Http : POST /datasets?page=&pageSize=
Http --> Client : Dataset[]
Client --> UseCase : Dataset[]
UseCase --> Controller : Dataset[]
Controller --> Presenter : Dataset[]
Presenter -> View : render dataset table
View --> User : Show datasets list

@enduml


