@startuml
title Show comments on dataset use case
autonumber

actor "DataSupplier/\nDataQualityManager" as User

participant "DatasetListView" as DatasetList
participant "DatasetCommentsView" as View
participant "DatasetDetailPresenter" as Presenter
participant "datasets.controller.ts" as Controller
participant "uc.dataset" as UseCase
participant "CombinedClient" as Client
participant "Dataset API\nGET /datasets/{id}" as Http

User ->> DatasetList : Click on show comments
DatasetList ->> Controller : loadDatasetComments(datasetId)
Controller ->> UseCase : getDatasetComments(datasetId)
UseCase -> Client : getDatasetComments(datasetId)
Client ->> Http : GET /datasets/{id}/comments
Http ->> Client : DatasetComment[]
Client --> UseCase : DatasetComment[]
UseCase ->> Presenter : present(DatasetComment[])
Presenter ->> View : render(DatasetComment[])
View ->> User : Show dataset comments

@enduml