@startuml
title listCatalogDatasets use case
autonumber

actor User

participant "Catalog detail view" as View
participant "CatalogDetailPresenter" as Presenter
participant "catalogs.controller.ts" as Controller
participant "uc.dataset" as UseCase
participant "CombinedClient" as Client
participant "Dataset API\nGET /catalogs/{id}/datasets" as Http

User -> View : Request datasets section
View -> Presenter : mount(catalogId)
Presenter -> Controller : loadCatalogDatasets(catalogId, page, size)
Controller -> UseCase : listCatalogDatasets(catalogId, page, size)
UseCase -> Client : listCatalogDatasets(catalogId, page, size)
Client -> Http : GET /catalogs/{id}/datasets?page=&pageSize=
Http --> Client : DatasetSummary[]
Client --> UseCase : DatasetSummary[]
UseCase --> Controller : DatasetSummary[]
Controller --> Presenter : DatasetSummary[]
Presenter -> View : render dataset table
View --> User : Show datasets list

@enduml
