@startuml
title listQualityControllableDatasets use case
autonumber

actor User

participant "Quality control view" as View
participant "QualityControllableDatasetsPresenter" as Presenter
participant "datasets.controller.ts" as Controller
participant "uc.dataset" as UseCase
participant "CombinedClient" as Client
participant "Dataset API\nGET /datasets/qualityControllable" as Http

User -> View : Open quality controllable datasets
View -> Presenter : mount(controllerId)
Presenter -> Controller : loadQualityControllableDatasets(controllerId)
Controller -> UseCase : listQualityControllableDatasets(controllerId)
UseCase -> Client : listQualityControllableDatasets(controllerId)
Client -> Http : GET /datasets/qualityControllable?controllerId={controllerId}
Http --> Client : DatasetSummary[]
Client --> UseCase : DatasetSummary[]
UseCase --> Controller : DatasetSummary[]
Controller --> Presenter : DatasetSummary[]
Presenter -> View : render quality controllable datasets
View --> User : Show datasets list

@enduml


