@startuml
title listQualityControllableDatasets use case
autonumber

actor DataQualityManager as User

participant "MainView" as MainView
participant "Quality control view" as View
participant "QualityControllableDatasetsPresenter" as Presenter
participant "datasets.controller.ts" as Controller
participant "uc.dataset" as UseCase
participant "CombinedClient" as Client
participant "Dataset API\nGET /datasets/qualityControllable" as Http

User ->> MainView : Open quality controllable datasets
MainView ->> Controller : loadQualityControllableDatasets(controllerId)
Controller ->> UseCase : listQualityControllableDatasets(controllerId)
UseCase -> Client : listQualityControllableDatasets(controllerId)
Client ->> Http : GET /datasets/qualityControllable?controllerId={controllerId}
Http ->> Client : DatasetSummary[]
Client --> UseCase : DatasetSummary[]
UseCase ->> Presenter : present(DatasetSummary[])
Presenter ->> View : render(DatasetSummary[])
View ->> User : Show datasets list

@enduml                                                                      
